export const worldCupCopy = {
  nav: {
    worldCupPredictions: "Predictions",
    advancedPredictions: "Bracket picks",
    predictionStats: "Prediction stats",
    rummyScores: "Rummy Scores",
    standings: "Standings",
    myPoints: "My Points",
    groups: "Home",
  },
  prediction: {
    alreadyPredicted: "Already predicted",
    bonusNotPredicted: "Bonus not predicted",
    duePrediction: "Due prediction",
    save: "Save prediction",
    update: "Update prediction",
    saved: "Prediction saved!",
    whoWillWin: "Who will win?",
    howWillItEnd: "How will the match end?",
    draw: "Draw",
    groupStageDrawHint:
      "Group stage matches can end in a tie. Knockout matches always have a winner after extra time or penalties.",
    makePrediction: "Make your prediction",
    viewOrUpdate: "View or update",
    bonusWatchHint:
      "Watch for bonus prompts—organizers may post questions on this match before kickoff.",
    yourPick: "Your pick",
    startLabel: "Start",
  },
  advancedBracket: {
    title: "Advanced bracket predictions",
    subtitle: "Pick semi-finalists, finalists, and the champion before the knockouts begin.",
    semiFinalists: "Semi-finalists",
    semiFinalistsHint: "Choose 4 teams you think will reach the semi-finals (10 points each, no penalty for misses).",
    finalists: "Finalists",
    finalistsHint: "Choose 2 teams you think will reach the final (15 points each).",
    winner: "Champion",
    winnerHint: "Pick the tournament winner (20 points).",
    teamsSelected: (n: number, max: number) => `${n} of ${max} selected`,
    save: "Save bracket picks",
    update: "Update bracket picks",
    saved: "Bracket picks saved!",
    locked: "Bracket picks are locked — knockouts have started.",
    notOpenYet: "Bracket picks open when your organizer reveals the Round of 32.",
    pointsTitle: "How bracket scoring works",
    pointsSemi: "10 points per correct semi-finalist (up to 4)",
    pointsFinal: "15 points per correct finalist (up to 2)",
    pointsWinner: "20 points for the correct champion",
    scoredAfterSemi: "Semi-finalist scoring runs after the semi-finals stage ends.",
    scoredAfterFinal: "Finalist and champion scoring runs after the final.",
    officialSemi: "Official semi-finalists",
    officialFinal: "Official finalists",
    officialWinner: "Official champion",
    notScoredYet: "Not scored yet",
  },
  admin: {
    panelTitle: "Admin tools",
    panelHint: "Enter a member's prediction on their behalf before lock time.",
    memberLabel: "Member",
    chooseMember: "Choose a member…",
    loadingMember: "Loading member predictions…",
    winnerPickLabel: "Winner pick",
    savePrediction: "Save member prediction",
    updatePrediction: "Update member prediction",
    predictionSaved: "Member prediction saved.",
    saveBonus: "Save member bonus",
    updateBonus: "Update member bonus",
    unlockPredictions: "Unlock predictions",
    unlockHint:
      "Predictions are locked. Unlock to reset the lock time to kickoff so you can enter member picks.",
    unlockSuccess: "Predictions unlocked until kickoff.",
    unlockKickoffPassed: "Kickoff has passed; predictions cannot be unlocked.",
    unlocking: "Unlocking…",
    postKickoffHint:
      "Kickoff has passed. You can still enter or update member picks using admin override.",
  },
  organizer: {
    officialResult: "Official result (90 minutes)",
    officialResultKnockout:
      "Enter the team that won the match (including extra time or penalties if needed).",
    officialResultGroup:
      "Enter the result after 90 minutes — home win, away win, or draw.",
    saveResult: "Save official result",
    resultSaved: "Official result saved.",
  },
  bonus: {
    sectionTitle: "Bonus question",
    optional: "Optional — only on matches your organizer adds one.",
    save: "Save bonus answer",
    update: "Update bonus answer",
    saved: "Bonus answer saved!",
    organizerTitle: "Bonus question (optional)",
    organizerHint: "Add a fun extra question for this match. Members pick one answer before lock.",
    questionLabel: "Question",
    choicesLabel: "Answer choices",
    choicesHint: "Members pick one option. Add at least two choices.",
    correctPoints: "Points if correct",
    wrongPoints: "Points if wrong",
    officialAnswer: "Official correct answer",
    addQuestion: "Add bonus question",
    removeQuestion: "Remove",
    setOfficial: "Set official answer for scoring",
    applyBonusScore: "Apply bonus score",
    bonusScored: "Bonus scoring applied.",
    pointsHint: "Use 0 for wrong if you only want to reward correct answers. Enter a positive number to subtract that many points.",
  },
  matchStatus: {
    open: "Open",
    locked: "Locked",
    done: "Done",
    scheduled: "Coming soon",
  },
  errors: {
    notOpenYet: "This round is not open yet. Check back when your group owner opens it.",
    predictionsClosed: "Predictions are closed for this match.",
    predictionRejectedAtLock: "The lock time passed. Your prediction was not saved.",
    importFailed: "We could not load the schedule. Check the CSV files and try again.",
    ownerOnly: "Only the group owner can do that.",
    voidReasonRequired: "Please say why this match is being voided.",
  },
  placeholderTeam: (name: string) =>
    name.includes("Playoff") || name.includes("TBD") || name.includes("Winner")
      ? "TBD (playoff winner)"
      : name,
} as const;
